Transform: AWS::Serverless-2016-10-31
Description: Concierge

Parameters:
  BucketName:
    Type: String

  RekognitionCollectionID:
    Type: String

  TeamsWebhook:
    Type: String

  WebhookURL:
    Type: String

  DeviceName:
    Type: String

  IoTEndpoint:
    Type: String

  IoTTopic:
    Type: String
    
  IoTTopicRateLimited:
    Type: String
    
  IsDeeplensUpsideDown:
    Type: String

  OpenDelaySeconds:
    Type: String

  RelayUsbDevice: 
    Type: String

  DynamoDBTableName: 
    Type: String

  SlackOauthAccessToken:
    Type: String

  SlackChannelId:
    Type: String

Resources:
  bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOld
            Status: Enabled
            ExpirationInDays: 2

  conciergeApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: concierge-api
      StageName: api
      DefinitionBody:
        swagger: 2.0
        info:
          title: !Ref AWS::StackName
        paths:
          /faces/train:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${train.Arn}/invocations
              responses: {}
            options:
              consumes:
                - application/json
              produces:
                - application/json
              responses:
                '200':
                  description: 200 response
                  schema:
                    $ref: '#/definitions/Empty'
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Headers:
                      type: string
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Methods: "'GET,PUT,DELETE,HEAD,OPTIONS'"
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                passthroughBehavior: when_no_match
                requestTemplates:
                  application/json: "{\"statusCode\": 200}"
                type: mock

# IAM roles
  trainRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: "s3_rekognition"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:PutObjectAcl"
                  - "s3:GetObject"
                  - "s3:DeleteObject"
                Resource: !Sub arn:aws:s3:::${BucketName}/*
              -
                Effect: "Allow"
                Action:
                  - "rekognition:DetectFaces"
                  - "rekognition:SearchFacesByImage"
                  - "rekognition:IndexFaces"
                Resource: !Sub arn:aws:rekognition:${AWS::Region}:${AWS::AccountId}:collection/${RekognitionCollectionID}

  guessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSIoTDataAccess
      Policies:
        - PolicyName: "s3_rekognition_iot"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:PutObjectAcl"
                  - "s3:GetObject"
                  - "s3:DeleteObject"
                Resource: !Sub arn:aws:s3:::${BucketName}/*
              -
                Effect: "Allow"
                Action:
                  - "rekognition:DetectFaces"
                  - "rekognition:SearchFacesByImage"
                  - "rekognition:IndexFaces"
                Resource: !Sub arn:aws:rekognition:${AWS::Region}:${AWS::AccountId}:collection/${RekognitionCollectionID}
              -
                Effect: "Allow"
                Action:
                  - "iot:DescribeEndpoint"
                Resource: "*"

  backendRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccesswithDataPipeline
        - arn:aws:iam::aws:policy/AWSIoTDataAccess 
      Policies:
        - PolicyName: "s3"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:PutObjectAcl"
                  - "s3:GetObject"
                  - "s3:DeleteObject"
                Resource: !Sub arn:aws:s3:::${BucketName}/*

  greengrassRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSIoTDataAccess
      Policies:
        - PolicyName: "s3"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:PutObjectAcl"
                Resource:
                  - !Sub arn:aws:s3:::${BucketName}
                  - !Sub arn:aws:s3:::${BucketName}/*
                  - !Sub ARN:aws:s3:::${BucketName}*

# lambda functions
  train:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: concierge-train
      Description: "concierge - train function"
      Handler: main
      Role: !GetAtt trainRole.Arn
      Runtime: go1.x
      MemorySize: 1024
      Timeout: 10
      CodeUri: ./source/train/deployment.zip
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          REKOGNITION_COLLECTION_ID: !Ref RekognitionCollectionID
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref conciergeApi
            Path: /faces/train
            Method: post

  guess:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: concierge-guess
      Description: "concierge - guess function"
      Handler: main
      Role: !GetAtt guessRole.Arn
      Runtime: go1.x
      MemorySize: 1024
      Timeout: 16
      CodeUri: ./source/guess/deployment.zip
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          REKOGNITION_COLLECTION_ID: !Ref RekognitionCollectionID
          IOT_TOPIC: !Ref IoTTopic
      Events:
        imageEvent:
          Type: S3
          Properties:
            Bucket: !Ref bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: incoming/
  rateLimit:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: concierge-rate-limit
      Description: "concierge - limit rate of detection events"
      Handler: rate_limit.lambda_handler
      Role: !GetAtt backendRole.Arn
      Runtime: python2.7
      MemorySize: 2048
      Timeout: 10
      CodeUri: ./source/rate-limit/deployment.zip
      AutoPublishAlias: prod
      Environment:
        Variables:
          OPEN_RATE: 60
          UNKOWN_RATE: 60
          IOT_TOPPIC: !Ref IoTTopicRateLimited
          DYNAMODB_TABLE: !Ref DynamoDBTableName
      Events:
        detectedEvent:
          Type: IoTRule
          Properties:
            Sql: !Sub SELECT * FROM '${IoTTopic}'

  notifyTeams:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: concierge-notify-teams
      Description: "concierge - notify teams function"
      Handler: main
      Role: !GetAtt backendRole.Arn
      Runtime: go1.x
      MemorySize: 1024
      Timeout: 60
      CodeUri: ./source/notify-teams/deployment.zip
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          TEAMS_WEBHOOK: !Ref TeamsWebhook
          TRAIN_URL: !Sub https://${conciergeApi}.execute-api.${AWS::Region}.amazonaws.com/api/faces/train
      Events:
        rateLimitedEvent:
          Type: IoTRule
          Properties:
            Sql: !Sub SELECT * FROM '${IoTTopicRateLimited}'

  triggerWebhook:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: concierge-trigger-webhook
      Description: "concierge - trigger generic webhook function"
      Handler: trigger_webhook.function_handler
      Role: !GetAtt backendRole.Arn
      Runtime: python3.7
      MemorySize: 128
      Timeout: 60
      CodeUri: ./source/trigger-webhook/deployment.zip
      Environment:
        Variables:
          WEBHOOK_URL: !Ref WebhookURL
      Events:
        rateLimitedEvent:
          Type: IoTRule
          Properties:
            Sql: !Sub SELECT * FROM '${IoTTopicRateLimited}'

  notifySlack:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: concierge-notify-slack
      Description: "concierge - trigger notify slack function"
      Handler: notify_slack.function_handler
      Role: !GetAtt backendRole.Arn
      Runtime: python3.7
      MemorySize: 128
      Timeout: 60
      CodeUri: ./source/notify-slack/deployment.zip
      Environment:
        Variables:
          SLACK_API_URL: https://slack.com/api/
          SLACK_API_TOKEN: sdf
          SLACK_CHANNEL_ID: !Ref SlackChannelId
          BUCKET_NAME: !Ref BucketName
      Events:
        rateLimitedEvent:
          Type: IoTRule
          Properties:
            Sql: !Sub SELECT * FROM '${IoTTopicRateLimited}'
  trainSlack:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: concierge-train-slack
      Description: "concierge - trigger train½ slack function"
      Handler: notify_slack.train
      Role: !GetAtt trainRole.Arn
      Runtime: python3.7
      MemorySize: 128
      Timeout: 60
      CodeUri: ./source/train-slack/deployment.zip
      Environment:
        Variables:
          SLACK_API_URL: https://slack.com/api/
          SLACK_API_TOKEN: !Ref SlackOauthAccessToken
          SLACK_CHANNEL_ID: !Ref SlackChannelId
          BUCKET_NAME: !Ref BucketName
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref conciergeApi
            Path: /faces/train-slack
            Method: post

            # greengrass
  findPerson:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: concierge-find-person
      Description: "concierge - find person function (greengrass)"
      Handler: find_person.function_handler
      Role: !GetAtt greengrassRole.Arn
      Runtime: python2.7
      MemorySize: 2048
      Timeout: 10
      CodeUri: ./source/find-person/dist/deployment.zip
      AutoPublishAlias: prod
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          IS_DEEPLENS_UPSIDE_DOWN: !Ref IsDeeplensUpsideDown

  triggerOpen:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: concierge-trigger-open
      Description: "concierge - trigger open function (greengrass)"
      Handler: trigger_open.function_handler
      Role: !GetAtt greengrassRole.Arn
      Runtime: python2.7
      MemorySize: 128
      Timeout: 10
      CodeUri: ./source/trigger-open/dist/deployment.zip
      AutoPublishAlias: prod
      Environment:
        Variables:
          DEVICE_NAME: !Ref DeviceName
          IOT_ENDPOINT: !Ref IoTEndpoint
          IOT_TOPIC: !Ref IoTTopic
          DeepLensDeviceReadAndWrite: !Ref RelayUsbDevice 
          USB_RELAY: !Ref RelayUsbDevice 
          OPEN_DELAY_SECONDS: !Ref OpenDelaySeconds

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Ref DynamoDBTableName
      AttributeDefinitions: 
        - AttributeName: "name"
          AttributeType: "S"
        - AttributeName: "selector"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "name"
          KeyType: "HASH"
        - AttributeName: "selector"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5


Outputs:
  apiurl:
    Description: API url
    Value: !Sub https://${conciergeApi}.execute-api.${AWS::Region}.amazonaws.com/api

